sonar.projectKey=Member-Claims-Platform
sonar.working.directory=C:\\ADO\\bupa\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\ADO\\bupa
sonar.pullrequest.cache.basepath=C:\\ADO\\bupa
sonar.sources=\
"C:\\ADO\\bupa\\.github\\workflows\\ci.yml",\
"C:\\ADO\\bupa\\.github\\workflows\\reusable-dotnet-ci.yml"

7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.projectKey=Member-Claims-Platform:7205BE0E-1181-4044-AB1F-E42CC051C48F
7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.projectName=MemberClaims.Api
7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.projectBaseDir=C:\\ADO\\bupa\\src\\MemberClaims.Api
7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.sourceEncoding=utf-8
7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.tests=
7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.sources=\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\Models\\Claim.cs",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\Program.cs",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Release\\net9.0\\MemberClaims.Api.GlobalUsings.g.cs",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Release\\net9.0\\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Release\\net9.0\\MemberClaims.Api.AssemblyInfo.cs",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Release\\net9.0\\MemberClaims.Api.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\appsettings.Development.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\appsettings.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\MemberClaims.Api.http",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\Properties\\launchSettings.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\MemberClaims.Api.csproj.nuget.dgspec.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\project.assets.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Debug\\net9.0\\appsettings.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Debug\\net9.0\\MemberClaims.Api.deps.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Debug\\net9.0\\MemberClaims.Api.runtimeconfig.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Debug\\net9.0\\MemberClaims.Api.staticwebassets.endpoints.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Release\\net9.0\\appsettings.Development.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Release\\net9.0\\appsettings.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Release\\net9.0\\MemberClaims.Api.deps.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Release\\net9.0\\MemberClaims.Api.runtimeconfig.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\bin\\Release\\net9.0\\MemberClaims.Api.staticwebassets.endpoints.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Debug\\net9.0\\MemberClaims.Api.sourcelink.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Debug\\net9.0\\staticwebassets.build.endpoints.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Debug\\net9.0\\staticwebassets.build.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Release\\net9.0\\MemberClaims.Api.sourcelink.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Release\\net9.0\\staticwebassets.build.endpoints.json",\
"C:\\ADO\\bupa\\src\\MemberClaims.Api\\obj\\Release\\net9.0\\staticwebassets.build.json"

7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.cs.analyzer.projectOutPaths=\
"C:\\ADO\\bupa\\.sonarqube\\out\\0"
7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.cs.roslyn.reportFilePaths=\
"C:\\ADO\\bupa\\.sonarqube\\out\\0\\Issues.json"
7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.cs.scanner.telemetry=\
"C:\\ADO\\bupa\\.sonarqube\\out\\0\\Telemetry.json"

7205BE0E-1181-4044-AB1F-E42CC051C48F.sonar.working.directory=C:\\ADO\\bupa\\.sonarqube\\out\\.sonar\\mod0
7F899507-F79F-4190-9458-60E7C8C28552.sonar.projectKey=Member-Claims-Platform:7F899507-F79F-4190-9458-60E7C8C28552
7F899507-F79F-4190-9458-60E7C8C28552.sonar.projectName=MemberClaims.UnitTests
7F899507-F79F-4190-9458-60E7C8C28552.sonar.projectBaseDir=C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests
7F899507-F79F-4190-9458-60E7C8C28552.sonar.sourceEncoding=utf-8
7F899507-F79F-4190-9458-60E7C8C28552.sonar.sources=
7F899507-F79F-4190-9458-60E7C8C28552.sonar.tests=\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\obj\\MemberClaims.UnitTests.csproj.nuget.dgspec.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\obj\\project.assets.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Debug\\net9.0\\appsettings.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Debug\\net9.0\\MemberClaims.Api.deps.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Debug\\net9.0\\MemberClaims.Api.runtimeconfig.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Debug\\net9.0\\MemberClaims.Api.staticwebassets.endpoints.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Debug\\net9.0\\MemberClaims.UnitTests.deps.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Debug\\net9.0\\MemberClaims.UnitTests.runtimeconfig.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Release\\net9.0\\appsettings.Development.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Release\\net9.0\\appsettings.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Release\\net9.0\\MemberClaims.Api.deps.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Release\\net9.0\\MemberClaims.Api.runtimeconfig.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Release\\net9.0\\MemberClaims.Api.staticwebassets.endpoints.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Release\\net9.0\\MemberClaims.UnitTests.deps.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\bin\\Release\\net9.0\\MemberClaims.UnitTests.runtimeconfig.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\obj\\Debug\\net9.0\\MemberClaims.UnitTests.sourcelink.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\obj\\Release\\net9.0\\MemberClaims.UnitTests.sourcelink.json",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\ClaimTests.cs",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\TestResults\\3726a911-aba3-45a3-a3ea-a3928024b298\\coverage.cobertura.xml",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\TestResults\\swarn_SWARNA-HP-LAP_2026-08-19_19_38_06\\In\\SWARNA-HP-LAP\\coverage.cobertura.xml",\
"C:\\ADO\\bupa\\tests\\MemberClaims.UnitTests\\TestResults\\test-results.trx"

7F899507-F79F-4190-9458-60E7C8C28552.sonar.cs.analyzer.projectOutPaths=\
"C:\\ADO\\bupa\\.sonarqube\\out\\1"
7F899507-F79F-4190-9458-60E7C8C28552.sonar.cs.roslyn.reportFilePaths=\
"C:\\ADO\\bupa\\.sonarqube\\out\\1\\Issues.json"
7F899507-F79F-4190-9458-60E7C8C28552.sonar.cs.scanner.telemetry=\
"C:\\ADO\\bupa\\.sonarqube\\out\\1\\Telemetry.json"

7F899507-F79F-4190-9458-60E7C8C28552.sonar.working.directory=C:\\ADO\\bupa\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=7205BE0E-1181-4044-AB1F-E42CC051C48F,7F899507-F79F-4190-9458-60E7C8C28552

