name: Member Claims CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/reusable-dotnet-ci.yml
    with:
      solution: MemberClaims.sln
      dotnet-version: '9.0.x'
      build-configuration: 'Release'